name: ecommerce_woocom
description: "Woocom ecommerce flutter project."
publish_to: 'CodeCanyon'
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cached_network_image:
  google_fonts:
  go_router: 
  flutter_riverpod:
  flutter_screenutil:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/brands/
    - assets/images/collection/
    - assets/images/product/
    - assets/images/grid/web/
    - assets/images/grid/mobile/
    - assets/icons/
