// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNUX2DzRIHFj8sEOciHFlZ1B7Euc81Ubg',
    appId: '1:218237534945:web:db4d2911ae6c01f095eda0',
    messagingSenderId: '218237534945',
    projectId: 'woocom-365a6',
    authDomain: 'woocom-365a6.firebaseapp.com',
    storageBucket: 'woocom-365a6.firebasestorage.app',
    measurementId: 'G-Q6GS7KFJQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFsKWtNvRUWQ7LJNEgE-OrgnVhWh2n6Xo',
    appId: '1:218237534945:android:e0f6f733a4a56d9e95eda0',
    messagingSenderId: '218237534945',
    projectId: 'woocom-365a6',
    storageBucket: 'woocom-365a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC2vhT9jksUhxy4Bv4h1mK6FdJfwIuKtc',
    appId: '1:218237534945:ios:0b4f2a19d119aaea95eda0',
    messagingSenderId: '218237534945',
    projectId: 'woocom-365a6',
    storageBucket: 'woocom-365a6.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceWoocom',
  );

}